@echo off
set VIRTUAL_ENV=D:\dev\ecnunote\env

if not defined PROMPT (
    set PROMPT=$P$G
)

if defined _OLD_VIRTUAL_PROMPT (
    set PROMPT=%_OLD_VIRTUAL_PROMPT%
)

if defined _OLD_VIRTUAL_PYTHONHOME (
     set PYTHONHOME=%_OLD_VIRTUAL_PYTHONHOME%
)

if defined _OLD_VIRTUAL_PYTHONPATH (
     set PYTHONPATH=%_OLD_VIRTUAL_PYTHONPATH%
)

set _OLD_VIRTUAL_PROMPT=%PROMPT%
set PROMPT=(env) %PROMPT%

if defined PYTHONHOME (
     set _OLD_VIRTUAL_PYTHONHOME=%PYTHONHOME%
     set PYTHONHOME=%VIRTUAL_ENV%
)

if defined PYTHONPATH (
     set _OLD_VIRTUAL_PYTHONPATH=%PYTHONPATH%
     set PYTHONPATH=C:\Python27\Scripts;C:\Python27\Lib;C:\Python27\DLLs
)

if defined _OLD_VIRTUAL_PATH set PATH=%_OLD_VIRTUAL_PATH%; goto SKIPPATH

set _OLD_VIRTUAL_PATH=%PATH%

:SKIPPATH
set PATH=%VIRTUAL_ENV%\Scripts;

:END
