#!D:\dev\ecnunote\env\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'markdown==2.2.0','markdown_py'
__requires__ = 'markdown==2.2.0'
import pkg_resources
pkg_resources.run_script('markdown==2.2.0', 'markdown_py')
